# Generated by Django 5.2.8 on 2026-03-01 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('blood_pressure', models.BooleanField(default=False)),
                ('allergies', models.BooleanField(default=False)),
                ('bleeding_disorders', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('pregnancy', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('previous_dental_surgery', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical History',
                'verbose_name_plural': 'Medical Histories',
            },
        ),
    ]
