# Generated by Django 5.2.8 on 2025-11-28

import django.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    related_name='patient_profile',
                    serialize=False,
                    to=settings.AUTH_USER_MODEL
                )),
                ('date_of_birth', models.DateField(
                    db_index=True,
                    validators=[utils.validators.validate_date_of_birth]
                )),
                ('phone_number', models.CharField(
                    db_index=True,
                    max_length=20,
                    validators=[django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex='^\\+?1?\\d{9,15}$'
                    )]
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(
                fields=['date_of_birth', 'phone_number'],
                name='patient_dob_phone_idx'
            ),
        ),
    ]
