# Generated by Django 5.2.8 on 2025-11-28

import django.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_patient_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    related_name='doctor_profile',
                    serialize=False,
                    to=settings.AUTH_USER_MODEL
                )),
                ('phone_number', models.CharField(
                    db_index=True,
                    max_length=20,
                    validators=[django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex='^\\+?1?\\d{9,15}$'
                    )]
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(
                fields=['phone_number'],
                name='doctor_phone_idx'
            ),
        ),
    ]
