# Generated by Django 5.1.4 on 2025-11-28 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_two_factor_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Temporary token for 2FA verification', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two-Factor Token',
                'verbose_name_plural': 'Two-Factor Tokens',
                'indexes': [models.Index(fields=['token', 'is_used'], name='tfa_token_used_idx'), models.Index(fields=['expires_at'], name='tfa_token_expires_idx')],
            },
        ),
    ]
