# Generated by Django 5.2.8 on 2025-11-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_two_factor_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Google OAuth user ID',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(
                choices=[('email', 'Email'), ('google', 'Google')],
                db_index=True,
                default='email',
                help_text='Authentication provider used for registration',
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['google_id'], name='user_google_id_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['auth_provider'], name='user_auth_provider_idx'),
        ),
    ]
